### ISSUE TITLE
Implement an option to set the window at the beginning of the list

### ISSUE THREAD

**Issue by r-darwish** [ktr0731/go-fuzzyfinder#126]

**Comment by ktr0731** [comment]
I'm sorry, I couldn't know what you want to support...
Could you provide more described information (what and why) for the feature?

**Comment by r-darwish** [comment]
Sure. I develop [IDNT](https://github.com/r-darwish/idnt) on the top of this library, and as you can see [in this screenshot](https://github.com/r-darwish/idnt/blob/master/doc/screenshot1.png), once you get the list your cursor is at the last entry instead of the first one. So instead of scrolling the list down the user need to scroll it up, and every time they press `tab` to select an entry, the cursor goes down again. It would make sense to have an option that points the cursor on the first entry instead of the last one.

**Comment by ktr0731** [comment]
I understand. Thanks for the clear explanation!
I think it makes sense to provide such a feature. 
Although you can sort the input list in reverse order in Go code when the input is not a stream, it's not an efficient way when the input is a stream or large.
