### ISSUE TITLE
hotreload has data race

### ISSUE THREAD

**Issue by JackKCWong** [ktr0731/go-fuzzyfinder#139]
## There is data race detected by `go run -race` 
when `fuzzyfinder.WithHotReload()` is enabled. e.g. in the `example/hotreload/main.go`

## To reproduce
```
cd example/hotreload
cat main.go | go run -race main.go
```

## Expected behavior
It can finish without data race.

## Screenshots
<img width="668" alt="image" src="https://user-images.githubusercontent.com/19254763/154490214-529c42b0-099f-4255-8c3e-eb77b4fb8641.png">

## Environment
- OS: MacOS
- Terminal: iTerm2
- go-fuzzyfinder version: commit `81ff9cb` dated 2022-01-10

**Comment by JackKCWong** [comment]
First of all, a fantastic library! I've been looking for sth like this for a long time. And this works across Win/Mac is just amazing :)

I think the issue here is pointer to slice is not safe for concurrent access. Maybe it can use sth like `atomic.Value`.

I can send a PR if you think that's the right idea. :)

**Comment by ktr0731** [comment]
I'm sorry for the late reply.
Can you please wait a few days, as I don't have the time to do a code review at the moment? 🙏

**Comment by JackKCWong** [comment]
sure, no rush :)

**Comment by ktr0731** [comment]
This issue has been fixed in #141
