### ISSUE TITLE
Feature: Consider switching to pure tcell instead of tcell/termbox

### ISSUE THREAD

**Issue by mnowotnik** [ktr0731/go-fuzzyfinder#15]
This package currently uses termbox emulation layer provided by tcell. The same UI could be coded with pure tcell API which would open up more opportunities for this project to grow.

One such functionality that would be possible with tcell API is rendering fuzzyfinder below prompt, like fzf. Actually fzf uses tcell behind the hood just to do that.

**Comment by ktr0731** [comment]
tcell has a problem that causes https://github.com/ktr0731/go-fuzzyfinder/issues/17. So, we can't switch it immediately.
