### ISSUE TITLE
Programmatic search

### ISSUE THREAD

**Issue by trpstra** [ktr0731/go-fuzzyfinder#168]
Thanks, this is really useful. 
I was wondering whether it currently supports the slightly different use case where input characters are coming in via some channel (another part of the program, not user input from the keyboard) and the output slice is reranked in response to the search terms coming in via that channel (no drawing on the terminal UI needed). 
Or, in case there is currently no easy way to support this, which part of the code I could start to look at to emulate this.
Cheers!

**Comment by ktr0731** [comment]
Sorry for the delay.
We don't expect such a use case since fuzzy finders are for users, not programs.
Maybe other generic libraries such as [fuzzysearch](https://github.com/lithammer/fuzzysearch) are a better choice.
