### ISSUE TITLE
the code is blocked on the function FindMulti  in case go-fuzzyfinder/_example/track

### ISSUE THREAD

**Issue by SmileEye** [ktr0731/go-fuzzyfinder#2]
Hello, when I run the example in Usage, the code is blocked on the function FindMulti.

go env:
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\smile\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\smile\go
set GOPROXY=
set GORACE=
set GOROOT=c:\go
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\smile\AppData\Local\Temp\go-build410240270=/tmp/go-build -gno-record-gcc-switches

**Comment by SmileEye** [comment]
I don't know where the configuration is wrong, Thank you for your help

**Comment by ktr0731** [comment]
What is your shell environment? Currently, I've tested only PowerShell and Command Prompt. (See https://github.com/ktr0731/go-fuzzyfinder/issues/1)

**Comment by SmileEye** [comment]
@ktr0731 There will be blocking problems when executing programs on git bash or goland ide. I changed bash to execute successfully. Thank you very much.

**Comment by suzuki-shunsuke** [comment]
I got the same issue on Windows.

## Environment

* Windows on Amazon Workspaces `Standard with Windows 10 (Server 2019 based) (PCoIP)`
* Git for Windows 2.36.1
* Git Bash
* MINGW64
* Go 1.18.3
* go-fuzzyfinder v0.6.0

## How to reproduce

main.go

```go
package main

import (
	"fmt"

	fuzzyfinder "github.com/ktr0731/go-fuzzyfinder"
)

func main() {
	slice := []struct {
		id   string
		name string
	}{
		{"id1", "foo"},
		{"id2", "bar"},
		{"id3", "baz"},
	}
	idxs, _ := fuzzyfinder.FindMulti(slice, func(i int) string {
		return fmt.Sprintf("[%s] %s", slice[i].id, slice[i].name)
	})
	for _, idx := range idxs {
		fmt.Println(slice[idx])
	}
}
```

go.mod

```
module foo

go 1.18

require github.com/ktr0731/go-fuzzyfinder v0.6.0

require (
	github.com/gdamore/encoding v1.0.0 // indirect
	github.com/gdamore/tcell/v2 v2.4.0 // indirect
	github.com/lucasb-eyer/go-colorful v1.0.3 // indirect
	github.com/mattn/go-runewidth v0.0.13 // indirect
	github.com/nsf/termbox-go v0.0.0-20201124104050-ed494de23a00 // indirect
	github.com/pkg/errors v0.9.1 // indirect
	github.com/rivo/uniseg v0.2.0 // indirect
	golang.org/x/sys v0.0.0-20210630005230-0f9fa26af87c // indirect
	golang.org/x/term v0.0.0-20201210144234-2321bbc49cbf // indirect
	golang.org/x/text v0.3.6 // indirect
)
```

Run main.go.

```console
$ go run main.go
```

Then the code is blocked.

<img width="598" alt="image" src="https://user-images.githubusercontent.com/13323303/173269048-d7a53560-9de1-4edb-8181-e87c74796f8e.png">

On the other hand, on M1 Mac the same code works well.

<img width="125" alt="image" src="https://user-images.githubusercontent.com/13323303/173270232-1690f11e-d9bf-4cd2-93a9-1fd1496d3551.png">

**Comment by suzuki-shunsuke** [comment]
The problem was solved by reinstalling Git for Windows, checking "Enable experimental support for pseudo consoles".

**Comment by ktr0731** [comment]
@suzuki-shunsuke 
Thank you for the report. Since I don't have any Windows environment, it's very helpful for us!
I'll add a notice about the pseudo consoles to README.md, implementation, or else.

**Comment by mttturek** [comment]
There is no option in the current installer to enable experimental support. Is there some newer workaround?
