### ISSUE TITLE
Ansi color in preview mode

### ISSUE THREAD

**Issue by davixcky** [ktr0731/go-fuzzyfinder#29]
## Describe the bug
I want to display text with Ansi colors (provided by github.com/logrusorgru/aurora). It's not possible, or it's not make sense?

## To reproduce
```
	projects, err := hbtn.GetProjects()
		if err != nil {
			log.Fatal(err)
		}

		idx, err := fuzzyfinder.FindMulti(
			projects,
			func(i int) string {
				return projects[i].Title
			},
			fuzzyfinder.WithPreviewWindow(func(i, w, h int) string {
				if i == -1 {
					return ""
				}

				return fmt.Sprintf("Track: %s (%s)\nAlbum: %s",
					Green(projects[i].Title),
					projects[i].Tasks,
					projects[i].ID)
			}))
		if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("selected: %v\n", idx)
```
## Screenshots
![image](https://user-images.githubusercontent.com/34346877/95527587-4ceb4500-099b-11eb-99aa-151b29e6550f.png)

## Environment
- OS: Arch linux
- Terminal: Tilix
- go-fuzzyfinder version: Latest

**Comment by ktr0731** [comment]
@davixcky 
I think it makes sense that providing ANSI color, and it's possible. 
Actually, fzf's preview window can display ANSI color-enabled text.

**Comment by RyanGreenup** [comment]
This would be a nice feature, what would be needed to get this working?

**Comment by ktr0731** [comment]
@RyanGreenup 
Hi, I'm sorry for the late reply.
Currently, `go-fuzzyfinder` can't interpret the ANSI escape code for the string returned from `WithPreviewWindow`. So, we need to implement it.

**Comment by RyanGreenup** [comment]
> So, we need to implement it.

I'm not a programmer by trade but I am trying to learn Go. If I manage to get some free time I'll  look at trying it, I think this would be really handy and would work really well with [*Glow*][1].

***
[1]: https://github.com/charmbracelet/glow

**Comment by danielfoehrKn** [comment]
That would be really nice to have, both for the main search window as well for the preview window.

**Comment by ktr0731** [comment]
This is now partially supported, but we are going to not publish a new version until the rest of the ANSI color codes will be implemented.

**Comment by ktr0731** [comment]
This is now fully supported by go-fuzzyfinder v0.7.0. Please try it out!
