### ISSUE TITLE
Previously entered text persists upon repeat executions of Find

### ISSUE THREAD

**Issue by martinbaillie** [ktr0731/go-fuzzyfinder#3]
I noticed the text I entered on a first `fuzz.Find*(...)` persisted on subsequent calls to `fuzz.Find*(...)` i.e. it's still their on the input line. Instantiating multiple finders fixes this.

I'm not sure this is desired so will raise a PR to clear state upon finder init.

By the way, thanks for the great project. I had started down the path of monkeypatching `fzf` to be a Go library before I found this!

**Comment by ktr0731** [comment]
Thank you for submitting an issue! It is unexpected behavior.
