### ISSUE TITLE
cross compile is no longer possible

### ISSUE THREAD

**Issue by mpon** [ktr0731/go-fuzzyfinder#43]
I used to use goreleaser to prepare cross-compiled binaries, but after updating to v0.3.1, I can't do it anymore.
I think the cause is [micmonay/keybd_event](https://github.com/micmonay/keybd_event/) that was included in this PR #32 . The relevant issue is here micmonay/keybd_event#2.

This is not an important issue for me, but as long as we continue to use this library, cross-compilation will be difficult.

I would be happy to hear the author's thoughts on this matter.

This is what I did when I tried it.
* https://github.com/mpon/ecswalk/actions/runs/477690778
* https://github.com/mpon/ecswalk/blob/master/.goreleaser.yaml

<img width="1415" alt="スクリーンショット 2021-01-11 23 37 17" src="https://user-images.githubusercontent.com/1325046/104195939-977ed080-5466-11eb-98a1-f4b906293f50.png">

**Comment by ktr0731** [comment]
Thanks, @mpon. 
I believe that this is a serious problem...
From the original issue, it looks like the Cgo dependency has not been resolved.
I'm trying to think of some workarounds, but if I can't think of any, I'm thinking of revert the PR.

**Comment by ktr0731** [comment]
This is fixed in v0.3.2.
