### ISSUE TITLE
seed string

### ISSUE THREAD

**Issue by kplimack** [ktr0731/go-fuzzyfinder#63]
Is there a way to supply an initial search string into the fuzzyfinder?  
for example:
```
./myFuzzyBrowser partialSearchTerm
```

can I feed the cmdline args into the finder without pre-filtering the slice I provide it ?

**Comment by ktr0731** [comment]
There is no way to provide a seed string to the finder, but it's possible to provide it as a new option.

> can I feed the cmdline args into the finder without pre-filtering the slice I provide it ?

It means that the finder has a seed string, but candidates are not filtered by it?
