### ISSUE TITLE
Possibility of adding a header?

### ISSUE THREAD

**Issue by Lilja** [ktr0731/go-fuzzyfinder#79]
Hi! Thanks for your project! I'm new to go and wondered if it's possible to add a header to the rows. FZF has this kind of support, see [this](https://github.com/junegunn/fzf/issues/346), and [this](https://github.com/junegunn/fzf/issues/296#issuecomment-123393182)

**Comment by ktr0731** [comment]
Hi, @Lilja. Thanks for your question.
Currently, `go-fuzzyfinder` doesn't have the header, but I think that we can support such feature.

**Comment by ktr0731** [comment]
@Lilja 
This feature has been introduced in [v0.5.0](https://github.com/ktr0731/go-fuzzyfinder/releases/tag/v0.5.0).
